### ISSUE TITLE
Make README more comprehensive.

### ISSUE THREAD

**Issue by JoelDesante** [JoelDesante/GameWump#11]
The `README.md` should have instructions on installation as well as a breif description of the project.

**Comment by JohnWesleyK** [comment]
Hey @JoelDesante can I work on this?

**Comment by JoelDesante** [comment]
> Hey @JoelDesante can I work on this?

Sure!

**Comment by JohnWesleyK** [comment]
Can you tell me how I can get started ?

**Comment by JohnWesleyK** [comment]
Can I get some notes?

**Comment by JoelDesante** [comment]
This is a pretty new project. So we don't have very many guidelines.
If you would like to fork the project and make your changes, I will be happy to merge them into the project after a breif review.

On the note of the README, we are currently working on some documentation which will be hosted at http://gamewump.com/docs

We would need a breif description that describes the bot a bit. It might be worth mentioning the following: 
- It's a Discord Bot
- The Bot is intended to bring iMessage text message style games to discord chats
